### ISSUE TITLE
UI Village Assistance Tool

### ISSUE THREAD

**Issue by bregord** [KayhanQ/GameOfHovels#10]
According to the spec, we need to have a tool that shows a player a list of their villages, and key info about them and the units they contain.

**Comment by KayhanQ** [comment]
Can you display all that info in Hud? Hud has the map object.

**Comment by bregord** [comment]
The entire HUD is basically done. We get info for selected units and villages. I tried to implement a basic jump-to village button, but I am having trouble getting it working
