### ISSUE TITLE
Villages don't turn into trees when they can't be supported anymore

### ISSUE THREAD

**Issue by bregord** [KayhanQ/GameOfHovels#14]
"If a region can no longer support a village after being invaded, the village is turned into a tree and the land converted to neutral  territory"

**Comment by KayhanQ** [comment]
Can you elaborate what case this would happen in?

**Comment by bregord** [comment]
If a unit invades an enemy village's territory, and the village's number of tiles numbers less than 3, the village should become a tree.

Basically, a village can only be supported if it has 3 tiles

**Comment by KayhanQ** [comment]
Ok cool missed that. That makes a lot of sense, easy fix! Keep the issues coming.
