### ISSUE TITLE
Gold is not falling below 1 due to upkeep

### ISSUE THREAD

**Issue by bregord** [KayhanQ/GameOfHovels#15]
A hovel with 4 tiles, 2 of which are trees, and 1 peasant should be losing gold each turn and it does. Once the gold counter gets to 1 however, no more gold is subtracted. This may be due to the tile that the village itself is on is adding gold to the treasury, which it probably shouldn't be doing.

**Comment by KayhanQ** [comment]
I think this only happens for the purple tiles simply because it is not the purple guys turn.
