### ISSUE TITLE
Crash if unit is tombstone while upgrade is open

### ISSUE THREAD

**Issue by bregord** [KayhanQ/GameOfHovels#20]
![screen shot 2015-04-04 at 4 35 14 pm](https://cloud.githubusercontent.com/assets/6232274/6994469/dd0c5c4c-dae8-11e4-8380-b3efa6302216.png)

When End Turn is pressed, it should close all menus. Otherwise, if a user presses the button to upgrade the app crashes

**Comment by KayhanQ** [comment]
Very true. I think I fixed i see if you can reproduce it.
